ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'USER';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "username" TEXT,
  ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;

ALTER TABLE "User"
  ALTER COLUMN "role" SET DEFAULT 'USER';

CREATE UNIQUE INDEX IF NOT EXISTS "User_username_key" ON "User"("username");
